version: "3.4"
services:
  radiance:
    build:
      context: .
      target: samples # Target stage. 'base', 'development', 'samples'
    volumes:
      - type: bind
        source: ./db  # Bind mount for Radiance's db and settings directory
        target: /db
      - type: bind
        source: ./apps  # Bind mount for directory with additional lisp systems
        target: /apps
    ports:
      # Port mappings have host on the left and container on the right
      - "8080:8080" # Port mapping for HTTP
      - "4005:4005" # Port mapping for slime
    environment:
      APP: # Additional lisp system to load
